// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        (unknown)
// source: redcarbon/external_api/agents/api/v1/v1.proto

package agentsExternalApiV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HZReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId    string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Ip         string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname   string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *HZReq) Reset() {
	*x = HZReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HZReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HZReq) ProtoMessage() {}

func (x *HZReq) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HZReq.ProtoReflect.Descriptor instead.
func (*HZReq) Descriptor() ([]byte, []int) {
	return file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescGZIP(), []int{0}
}

func (x *HZReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HZReq) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *HZReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HZReq) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type HZRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
}

func (x *HZRes) Reset() {
	*x = HZRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HZRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HZRes) ProtoMessage() {}

func (x *HZRes) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HZRes.ProtoReflect.Descriptor instead.
func (*HZRes) Descriptor() ([]byte, []int) {
	return file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescGZIP(), []int{1}
}

func (x *HZRes) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

type PullConfigurationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId    string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *PullConfigurationsReq) Reset() {
	*x = PullConfigurationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullConfigurationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullConfigurationsReq) ProtoMessage() {}

func (x *PullConfigurationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullConfigurationsReq.ProtoReflect.Descriptor instead.
func (*PullConfigurationsReq) Descriptor() ([]byte, []int) {
	return file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescGZIP(), []int{2}
}

func (x *PullConfigurationsReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PullConfigurationsReq) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type PullConfigurationsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullConfigurationsRes) Reset() {
	*x = PullConfigurationsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullConfigurationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullConfigurationsRes) ProtoMessage() {}

func (x *PullConfigurationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullConfigurationsRes.ProtoReflect.Descriptor instead.
func (*PullConfigurationsRes) Descriptor() ([]byte, []int) {
	return file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescGZIP(), []int{3}
}

type SendDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId    string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Data       string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendDataReq) Reset() {
	*x = SendDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataReq) ProtoMessage() {}

func (x *SendDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataReq.ProtoReflect.Descriptor instead.
func (*SendDataReq) Descriptor() ([]byte, []int) {
	return file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescGZIP(), []int{4}
}

func (x *SendDataReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendDataReq) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SendDataReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SendDataRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
}

func (x *SendDataRes) Reset() {
	*x = SendDataRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataRes) ProtoMessage() {}

func (x *SendDataRes) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataRes.ProtoReflect.Descriptor instead.
func (*SendDataRes) Descriptor() ([]byte, []int) {
	return file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescGZIP(), []int{5}
}

func (x *SendDataRes) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

var File_redcarbon_external_api_agents_api_v1_v1_proto protoreflect.FileDescriptor

var file_redcarbon_external_api_agents_api_v1_v1_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2f, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x24, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x05, 0x48, 0x5a, 0x52, 0x65, 0x71, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x05, 0x48, 0x5a, 0x52, 0x65, 0x73,
	0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x22, 0x53, 0x0a,
	0x15, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x22, 0x5d, 0x0a, 0x0b, 0x53,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x0b, 0x53, 0x65,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x32, 0xfe, 0x02, 0x0a, 0x13, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x56, 0x31, 0x53, 0x72, 0x76, 0x12, 0x60,
	0x0a, 0x02, 0x48, 0x5a, 0x12, 0x2b, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x5a, 0x52, 0x65,
	0x71, 0x1a, 0x2b, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x5a, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x90, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3b, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72,
	0x62, 0x6f, 0x6e, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x3b, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x6c, 0x6c,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x72, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x31, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x1a, 0x31, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x51, 0x5a, 0x4f, 0x70, 0x6b, 0x67, 0x2e, 0x72,
	0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x61, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2f, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x70, 0x69, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescOnce sync.Once
	file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescData = file_redcarbon_external_api_agents_api_v1_v1_proto_rawDesc
)

func file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescGZIP() []byte {
	file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescOnce.Do(func() {
		file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescData)
	})
	return file_redcarbon_external_api_agents_api_v1_v1_proto_rawDescData
}

var file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_redcarbon_external_api_agents_api_v1_v1_proto_goTypes = []interface{}{
	(*HZReq)(nil),                 // 0: redcarbon.external_api.agents.api.v1.HZReq
	(*HZRes)(nil),                 // 1: redcarbon.external_api.agents.api.v1.HZRes
	(*PullConfigurationsReq)(nil), // 2: redcarbon.external_api.agents.api.v1.PullConfigurationsReq
	(*PullConfigurationsRes)(nil), // 3: redcarbon.external_api.agents.api.v1.PullConfigurationsRes
	(*SendDataReq)(nil),           // 4: redcarbon.external_api.agents.api.v1.SendDataReq
	(*SendDataRes)(nil),           // 5: redcarbon.external_api.agents.api.v1.SendDataRes
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_redcarbon_external_api_agents_api_v1_v1_proto_depIdxs = []int32{
	6, // 0: redcarbon.external_api.agents.api.v1.HZRes.received_at:type_name -> google.protobuf.Timestamp
	6, // 1: redcarbon.external_api.agents.api.v1.SendDataRes.received_at:type_name -> google.protobuf.Timestamp
	0, // 2: redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv.HZ:input_type -> redcarbon.external_api.agents.api.v1.HZReq
	2, // 3: redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv.PullConfigurations:input_type -> redcarbon.external_api.agents.api.v1.PullConfigurationsReq
	4, // 4: redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv.SendData:input_type -> redcarbon.external_api.agents.api.v1.SendDataReq
	1, // 5: redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv.HZ:output_type -> redcarbon.external_api.agents.api.v1.HZRes
	3, // 6: redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv.PullConfigurations:output_type -> redcarbon.external_api.agents.api.v1.PullConfigurationsRes
	5, // 7: redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv.SendData:output_type -> redcarbon.external_api.agents.api.v1.SendDataRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_redcarbon_external_api_agents_api_v1_v1_proto_init() }
func file_redcarbon_external_api_agents_api_v1_v1_proto_init() {
	if File_redcarbon_external_api_agents_api_v1_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HZReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HZRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullConfigurationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullConfigurationsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDataRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redcarbon_external_api_agents_api_v1_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redcarbon_external_api_agents_api_v1_v1_proto_goTypes,
		DependencyIndexes: file_redcarbon_external_api_agents_api_v1_v1_proto_depIdxs,
		MessageInfos:      file_redcarbon_external_api_agents_api_v1_v1_proto_msgTypes,
	}.Build()
	File_redcarbon_external_api_agents_api_v1_v1_proto = out.File
	file_redcarbon_external_api_agents_api_v1_v1_proto_rawDesc = nil
	file_redcarbon_external_api_agents_api_v1_v1_proto_goTypes = nil
	file_redcarbon_external_api_agents_api_v1_v1_proto_depIdxs = nil
}
