// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: redcarbon/external_api/agents/api/v1/v1.proto

package agentsExternalApiV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentsExternalV1SrvClient is the client API for AgentsExternalV1Srv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentsExternalV1SrvClient interface {
	HZ(ctx context.Context, in *HZReq, opts ...grpc.CallOption) (*HZRes, error)
	PullConfigurations(ctx context.Context, in *PullConfigurationsReq, opts ...grpc.CallOption) (*PullConfigurationsRes, error)
	SendData(ctx context.Context, in *SendDataReq, opts ...grpc.CallOption) (*SendDataRes, error)
}

type agentsExternalV1SrvClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentsExternalV1SrvClient(cc grpc.ClientConnInterface) AgentsExternalV1SrvClient {
	return &agentsExternalV1SrvClient{cc}
}

func (c *agentsExternalV1SrvClient) HZ(ctx context.Context, in *HZReq, opts ...grpc.CallOption) (*HZRes, error) {
	out := new(HZRes)
	err := c.cc.Invoke(ctx, "/redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv/HZ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsExternalV1SrvClient) PullConfigurations(ctx context.Context, in *PullConfigurationsReq, opts ...grpc.CallOption) (*PullConfigurationsRes, error) {
	out := new(PullConfigurationsRes)
	err := c.cc.Invoke(ctx, "/redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv/PullConfigurations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsExternalV1SrvClient) SendData(ctx context.Context, in *SendDataReq, opts ...grpc.CallOption) (*SendDataRes, error) {
	out := new(SendDataRes)
	err := c.cc.Invoke(ctx, "/redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv/SendData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentsExternalV1SrvServer is the server API for AgentsExternalV1Srv service.
// All implementations should embed UnimplementedAgentsExternalV1SrvServer
// for forward compatibility
type AgentsExternalV1SrvServer interface {
	HZ(context.Context, *HZReq) (*HZRes, error)
	PullConfigurations(context.Context, *PullConfigurationsReq) (*PullConfigurationsRes, error)
	SendData(context.Context, *SendDataReq) (*SendDataRes, error)
}

// UnimplementedAgentsExternalV1SrvServer should be embedded to have forward compatible implementations.
type UnimplementedAgentsExternalV1SrvServer struct {
}

func (UnimplementedAgentsExternalV1SrvServer) HZ(context.Context, *HZReq) (*HZRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HZ not implemented")
}
func (UnimplementedAgentsExternalV1SrvServer) PullConfigurations(context.Context, *PullConfigurationsReq) (*PullConfigurationsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullConfigurations not implemented")
}
func (UnimplementedAgentsExternalV1SrvServer) SendData(context.Context, *SendDataReq) (*SendDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendData not implemented")
}

// UnsafeAgentsExternalV1SrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentsExternalV1SrvServer will
// result in compilation errors.
type UnsafeAgentsExternalV1SrvServer interface {
	mustEmbedUnimplementedAgentsExternalV1SrvServer()
}

func RegisterAgentsExternalV1SrvServer(s grpc.ServiceRegistrar, srv AgentsExternalV1SrvServer) {
	s.RegisterService(&AgentsExternalV1Srv_ServiceDesc, srv)
}

func _AgentsExternalV1Srv_HZ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HZReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsExternalV1SrvServer).HZ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv/HZ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsExternalV1SrvServer).HZ(ctx, req.(*HZReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsExternalV1Srv_PullConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullConfigurationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsExternalV1SrvServer).PullConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv/PullConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsExternalV1SrvServer).PullConfigurations(ctx, req.(*PullConfigurationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsExternalV1Srv_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsExternalV1SrvServer).SendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv/SendData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsExternalV1SrvServer).SendData(ctx, req.(*SendDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentsExternalV1Srv_ServiceDesc is the grpc.ServiceDesc for AgentsExternalV1Srv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentsExternalV1Srv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redcarbon.external_api.agents.api.v1.AgentsExternalV1Srv",
	HandlerType: (*AgentsExternalV1SrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HZ",
			Handler:    _AgentsExternalV1Srv_HZ_Handler,
		},
		{
			MethodName: "PullConfigurations",
			Handler:    _AgentsExternalV1Srv_PullConfigurations_Handler,
		},
		{
			MethodName: "SendData",
			Handler:    _AgentsExternalV1Srv_SendData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redcarbon/external_api/agents/api/v1/v1.proto",
}
