project_name: redcarbon

release:
  prerelease: auto
  name_template: "RedCarbon Agent {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/redcarbon
      main: ./cmd
      ldflags:
        - -s -w -X pkg.redcarbon.ai/internal/build.Version={{.Version}} -X pkg.redcarbon.ai/internal/build.Architecture={{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }} -X pkg.redcarbon.ai/internal/build.DefaultHost={{.Env.API_HOST}}
      env:
        - CGO_ENABLED=0
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

archives:
  - id: nix
    builds: [linux, macos]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz

nfpms:
  - license: MIT
    maintainer: RedCarbon
    homepage: https://redcarbon.ai
    bindir: /usr
    description: RedCarbon's Agent
    formats:
      - deb
      - rpm
