// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isAgentConfigurationData_Data is an autogenerated mock type for the isAgentConfigurationData_Data type
type isAgentConfigurationData_Data struct {
	mock.Mock
}

type isAgentConfigurationData_Data_Expecter struct {
	mock *mock.Mock
}

func (_m *isAgentConfigurationData_Data) EXPECT() *isAgentConfigurationData_Data_Expecter {
	return &isAgentConfigurationData_Data_Expecter{mock: &_m.Mock}
}

// isAgentConfigurationData_Data provides a mock function with given fields:
func (_m *isAgentConfigurationData_Data) isAgentConfigurationData_Data() {
	_m.Called()
}

// isAgentConfigurationData_Data_isAgentConfigurationData_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isAgentConfigurationData_Data'
type isAgentConfigurationData_Data_isAgentConfigurationData_Data_Call struct {
	*mock.Call
}

// isAgentConfigurationData_Data is a helper method to define mock.On call
func (_e *isAgentConfigurationData_Data_Expecter) isAgentConfigurationData_Data() *isAgentConfigurationData_Data_isAgentConfigurationData_Data_Call {
	return &isAgentConfigurationData_Data_isAgentConfigurationData_Data_Call{Call: _e.mock.On("isAgentConfigurationData_Data")}
}

func (_c *isAgentConfigurationData_Data_isAgentConfigurationData_Data_Call) Run(run func()) *isAgentConfigurationData_Data_isAgentConfigurationData_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *isAgentConfigurationData_Data_isAgentConfigurationData_Data_Call) Return() *isAgentConfigurationData_Data_isAgentConfigurationData_Data_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTnewIsAgentConfigurationData_Data interface {
	mock.TestingT
	Cleanup(func())
}

// newIsAgentConfigurationData_Data creates a new instance of isAgentConfigurationData_Data. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newIsAgentConfigurationData_Data(t mockConstructorTestingTnewIsAgentConfigurationData_Data) *isAgentConfigurationData_Data {
	mock := &isAgentConfigurationData_Data{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
