// Code generated by mockery v2.25.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAgentsPublicApiV1SrvServer is an autogenerated mock type for the UnsafeAgentsPublicApiV1SrvServer type
type UnsafeAgentsPublicApiV1SrvServer struct {
	mock.Mock
}

type UnsafeAgentsPublicApiV1SrvServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeAgentsPublicApiV1SrvServer) EXPECT() *UnsafeAgentsPublicApiV1SrvServer_Expecter {
	return &UnsafeAgentsPublicApiV1SrvServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedAgentsPublicApiV1SrvServer provides a mock function with given fields:
func (_m *UnsafeAgentsPublicApiV1SrvServer) mustEmbedUnimplementedAgentsPublicApiV1SrvServer() {
	_m.Called()
}

// UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedAgentsPublicApiV1SrvServer'
type UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedAgentsPublicApiV1SrvServer is a helper method to define mock.On call
func (_e *UnsafeAgentsPublicApiV1SrvServer_Expecter) mustEmbedUnimplementedAgentsPublicApiV1SrvServer() *UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call {
	return &UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call{Call: _e.mock.On("mustEmbedUnimplementedAgentsPublicApiV1SrvServer")}
}

func (_c *UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call) Run(run func()) *UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call) Return() *UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call) RunAndReturn(run func()) *UnsafeAgentsPublicApiV1SrvServer_mustEmbedUnimplementedAgentsPublicApiV1SrvServer_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUnsafeAgentsPublicApiV1SrvServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeAgentsPublicApiV1SrvServer creates a new instance of UnsafeAgentsPublicApiV1SrvServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeAgentsPublicApiV1SrvServer(t mockConstructorTestingTNewUnsafeAgentsPublicApiV1SrvServer) *UnsafeAgentsPublicApiV1SrvServer {
	mock := &UnsafeAgentsPublicApiV1SrvServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
