// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAgentsExternalV1SrvServer is an autogenerated mock type for the UnsafeAgentsExternalV1SrvServer type
type UnsafeAgentsExternalV1SrvServer struct {
	mock.Mock
}

type UnsafeAgentsExternalV1SrvServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeAgentsExternalV1SrvServer) EXPECT() *UnsafeAgentsExternalV1SrvServer_Expecter {
	return &UnsafeAgentsExternalV1SrvServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedAgentsExternalV1SrvServer provides a mock function with given fields:
func (_m *UnsafeAgentsExternalV1SrvServer) mustEmbedUnimplementedAgentsExternalV1SrvServer() {
	_m.Called()
}

// UnsafeAgentsExternalV1SrvServer_mustEmbedUnimplementedAgentsExternalV1SrvServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedAgentsExternalV1SrvServer'
type UnsafeAgentsExternalV1SrvServer_mustEmbedUnimplementedAgentsExternalV1SrvServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedAgentsExternalV1SrvServer is a helper method to define mock.On call
func (_e *UnsafeAgentsExternalV1SrvServer_Expecter) mustEmbedUnimplementedAgentsExternalV1SrvServer() *UnsafeAgentsExternalV1SrvServer_mustEmbedUnimplementedAgentsExternalV1SrvServer_Call {
	return &UnsafeAgentsExternalV1SrvServer_mustEmbedUnimplementedAgentsExternalV1SrvServer_Call{Call: _e.mock.On("mustEmbedUnimplementedAgentsExternalV1SrvServer")}
}

func (_c *UnsafeAgentsExternalV1SrvServer_mustEmbedUnimplementedAgentsExternalV1SrvServer_Call) Run(run func()) *UnsafeAgentsExternalV1SrvServer_mustEmbedUnimplementedAgentsExternalV1SrvServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeAgentsExternalV1SrvServer_mustEmbedUnimplementedAgentsExternalV1SrvServer_Call) Return() *UnsafeAgentsExternalV1SrvServer_mustEmbedUnimplementedAgentsExternalV1SrvServer_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewUnsafeAgentsExternalV1SrvServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeAgentsExternalV1SrvServer creates a new instance of UnsafeAgentsExternalV1SrvServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeAgentsExternalV1SrvServer(t mockConstructorTestingTNewUnsafeAgentsExternalV1SrvServer) *UnsafeAgentsExternalV1SrvServer {
	mock := &UnsafeAgentsExternalV1SrvServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
