// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        (unknown)
// source: redcarbon/public_apis/agents/api/v1/types.proto

package agentsPublicApiV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_UNSUPPORTED               DataType = 0
	DataType_SENTINEL_ONE              DataType = 1
	DataType_GRAYLOG_IMPOSSIBLE_TRAVEL DataType = 2
	DataType_GRAYLOG_DATAMINE          DataType = 3
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "UNSUPPORTED",
		1: "SENTINEL_ONE",
		2: "GRAYLOG_IMPOSSIBLE_TRAVEL",
		3: "GRAYLOG_DATAMINE",
	}
	DataType_value = map[string]int32{
		"UNSUPPORTED":               0,
		"SENTINEL_ONE":              1,
		"GRAYLOG_IMPOSSIBLE_TRAVEL": 2,
		"GRAYLOG_DATAMINE":          3,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_redcarbon_public_apis_agents_api_v1_types_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{0}
}

type AgentConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentConfigurationId string                  `protobuf:"bytes,1,opt,name=agent_configuration_id,json=agentConfigurationId,proto3" json:"agent_configuration_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name                 string                  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Data                 *AgentConfigurationData `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Type                 string                  `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *AgentConfiguration) Reset() {
	*x = AgentConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfiguration) ProtoMessage() {}

func (x *AgentConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfiguration.ProtoReflect.Descriptor instead.
func (*AgentConfiguration) Descriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *AgentConfiguration) GetAgentConfigurationId() string {
	if x != nil {
		return x.AgentConfigurationId
	}
	return ""
}

func (x *AgentConfiguration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentConfiguration) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AgentConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentConfiguration) GetData() *AgentConfigurationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AgentConfiguration) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AgentConfigurationData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*AgentConfigurationData_SentinelOne
	//	*AgentConfigurationData_GraylogImpossibleTravel
	//	*AgentConfigurationData_GraylogDatamine
	Data isAgentConfigurationData_Data `protobuf_oneof:"data"`
}

func (x *AgentConfigurationData) Reset() {
	*x = AgentConfigurationData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentConfigurationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigurationData) ProtoMessage() {}

func (x *AgentConfigurationData) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigurationData.ProtoReflect.Descriptor instead.
func (*AgentConfigurationData) Descriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{1}
}

func (m *AgentConfigurationData) GetData() isAgentConfigurationData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *AgentConfigurationData) GetSentinelOne() *SentinelOneData {
	if x, ok := x.GetData().(*AgentConfigurationData_SentinelOne); ok {
		return x.SentinelOne
	}
	return nil
}

func (x *AgentConfigurationData) GetGraylogImpossibleTravel() *GrayLogImpossibleTravelData {
	if x, ok := x.GetData().(*AgentConfigurationData_GraylogImpossibleTravel); ok {
		return x.GraylogImpossibleTravel
	}
	return nil
}

func (x *AgentConfigurationData) GetGraylogDatamine() *GrayLogDataMineData {
	if x, ok := x.GetData().(*AgentConfigurationData_GraylogDatamine); ok {
		return x.GraylogDatamine
	}
	return nil
}

type isAgentConfigurationData_Data interface {
	isAgentConfigurationData_Data()
}

type AgentConfigurationData_SentinelOne struct {
	SentinelOne *SentinelOneData `protobuf:"bytes,1,opt,name=sentinel_one,json=sentinelOne,proto3,oneof"`
}

type AgentConfigurationData_GraylogImpossibleTravel struct {
	GraylogImpossibleTravel *GrayLogImpossibleTravelData `protobuf:"bytes,2,opt,name=graylog_impossible_travel,json=graylogImpossibleTravel,proto3,oneof"`
}

type AgentConfigurationData_GraylogDatamine struct {
	GraylogDatamine *GrayLogDataMineData `protobuf:"bytes,3,opt,name=graylog_datamine,json=graylogDatamine,proto3,oneof"`
}

func (*AgentConfigurationData_SentinelOne) isAgentConfigurationData_Data() {}

func (*AgentConfigurationData_GraylogImpossibleTravel) isAgentConfigurationData_Data() {}

func (*AgentConfigurationData_GraylogDatamine) isAgentConfigurationData_Data() {}

type SentinelOneData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiToken string `protobuf:"bytes,1,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SentinelOneData) Reset() {
	*x = SentinelOneData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentinelOneData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentinelOneData) ProtoMessage() {}

func (x *SentinelOneData) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentinelOneData.ProtoReflect.Descriptor instead.
func (*SentinelOneData) Descriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *SentinelOneData) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *SentinelOneData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GrayLogImpossibleTravelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string               `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Url        string               `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	SkipSsl    bool                 `protobuf:"varint,3,opt,name=skip_ssl,json=skipSsl,proto3" json:"skip_ssl,omitempty"`
	TimeWindow *durationpb.Duration `protobuf:"bytes,4,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"`
}

func (x *GrayLogImpossibleTravelData) Reset() {
	*x = GrayLogImpossibleTravelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrayLogImpossibleTravelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrayLogImpossibleTravelData) ProtoMessage() {}

func (x *GrayLogImpossibleTravelData) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrayLogImpossibleTravelData.ProtoReflect.Descriptor instead.
func (*GrayLogImpossibleTravelData) Descriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *GrayLogImpossibleTravelData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GrayLogImpossibleTravelData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GrayLogImpossibleTravelData) GetSkipSsl() bool {
	if x != nil {
		return x.SkipSsl
	}
	return false
}

func (x *GrayLogImpossibleTravelData) GetTimeWindow() *durationpb.Duration {
	if x != nil {
		return x.TimeWindow
	}
	return nil
}

type GrayLogDataMineData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Url     string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	SkipSsl bool   `protobuf:"varint,3,opt,name=skip_ssl,json=skipSsl,proto3" json:"skip_ssl,omitempty"`
}

func (x *GrayLogDataMineData) Reset() {
	*x = GrayLogDataMineData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrayLogDataMineData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrayLogDataMineData) ProtoMessage() {}

func (x *GrayLogDataMineData) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrayLogDataMineData.ProtoReflect.Descriptor instead.
func (*GrayLogDataMineData) Descriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *GrayLogDataMineData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GrayLogDataMineData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GrayLogDataMineData) GetSkipSsl() bool {
	if x != nil {
		return x.SkipSsl
	}
	return false
}

type GrayLogImpossibleTravelLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs map[string]string `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GrayLogImpossibleTravelLog) Reset() {
	*x = GrayLogImpossibleTravelLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrayLogImpossibleTravelLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrayLogImpossibleTravelLog) ProtoMessage() {}

func (x *GrayLogImpossibleTravelLog) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrayLogImpossibleTravelLog.ProtoReflect.Descriptor instead.
func (*GrayLogImpossibleTravelLog) Descriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *GrayLogImpossibleTravelLog) GetLogs() map[string]string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type GrayLogDataMineResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Uuid      string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Source    string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GrayLogDataMineResult) Reset() {
	*x = GrayLogDataMineResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrayLogDataMineResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrayLogDataMineResult) ProtoMessage() {}

func (x *GrayLogDataMineResult) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrayLogDataMineResult.ProtoReflect.Descriptor instead.
func (*GrayLogDataMineResult) Descriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *GrayLogDataMineResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GrayLogDataMineResult) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GrayLogDataMineResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GrayLogDataMineResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GrayLogDataMineQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SearchStartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=search_start_time,json=searchStartTime,proto3" json:"search_start_time,omitempty"`
	SearchStopTime  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=search_stop_time,json=searchStopTime,proto3" json:"search_stop_time,omitempty"`
	Query           string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *GrayLogDataMineQuery) Reset() {
	*x = GrayLogDataMineQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrayLogDataMineQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrayLogDataMineQuery) ProtoMessage() {}

func (x *GrayLogDataMineQuery) ProtoReflect() protoreflect.Message {
	mi := &file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrayLogDataMineQuery.ProtoReflect.Descriptor instead.
func (*GrayLogDataMineQuery) Descriptor() ([]byte, []int) {
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *GrayLogDataMineQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GrayLogDataMineQuery) GetSearchStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SearchStartTime
	}
	return nil
}

func (x *GrayLogDataMineQuery) GetSearchStopTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SearchStopTime
	}
	return nil
}

func (x *GrayLogDataMineQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

var File_redcarbon_public_apis_agents_api_v1_types_proto protoreflect.FileDescriptor

var file_redcarbon_public_apis_agents_api_v1_types_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2f, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x23, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x02, 0x0a, 0x12, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34,
	0x0a, 0x16, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4f,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x72,
	0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0xe2, 0x02, 0x0a, 0x16, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x59,
	0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6c, 0x5f, 0x6f, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x74, 0x69,
	0x6e, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65,
	0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x12, 0x7e, 0x0a, 0x19, 0x67, 0x72, 0x61,
	0x79, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x5f,
	0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x72,
	0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x79, 0x4c, 0x6f, 0x67, 0x49, 0x6d, 0x70, 0x6f, 0x73, 0x73,
	0x69, 0x62, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x17, 0x67, 0x72, 0x61, 0x79, 0x6c, 0x6f, 0x67, 0x49, 0x6d, 0x70, 0x6f, 0x73, 0x73, 0x69,
	0x62, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x65, 0x0a, 0x10, 0x67, 0x72, 0x61,
	0x79, 0x6c, 0x6f, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x79, 0x4c, 0x6f,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52,
	0x0f, 0x67, 0x72, 0x61, 0x79, 0x6c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x65,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x74,
	0x69, 0x6e, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x61,
	0x70, 0x69, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x61, 0x70, 0x69, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x9c, 0x01, 0x0a, 0x1b, 0x47,
	0x72, 0x61, 0x79, 0x4c, 0x6f, 0x67, 0x49, 0x6d, 0x70, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65,
	0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x73, 0x73, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x70, 0x53, 0x73, 0x6c, 0x12, 0x3a, 0x0a,
	0x0b, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x22, 0x58, 0x0a, 0x13, 0x47, 0x72, 0x61,
	0x79, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x70,
	0x5f, 0x73, 0x73, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x70,
	0x53, 0x73, 0x6c, 0x22, 0xb4, 0x01, 0x0a, 0x1a, 0x47, 0x72, 0x61, 0x79, 0x4c, 0x6f, 0x67, 0x49,
	0x6d, 0x70, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x4c,
	0x6f, 0x67, 0x12, 0x5d, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x49, 0x2e, 0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x79, 0x4c, 0x6f, 0x67, 0x49, 0x6d,
	0x70, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x4c, 0x6f,
	0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x6f, 0x67,
	0x73, 0x1a, 0x37, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x97, 0x01, 0x0a, 0x15, 0x47,
	0x72, 0x61, 0x79, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xca, 0x01, 0x0a, 0x14, 0x47, 0x72, 0x61, 0x79, 0x4c, 0x6f, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x4d, 0x69, 0x6e, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x46, 0x0a,
	0x11, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x73, 0x74, 0x6f, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x2a, 0x62, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x54, 0x49, 0x4e, 0x45, 0x4c, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x01,
	0x12, 0x1d, 0x0a, 0x19, 0x47, 0x52, 0x41, 0x59, 0x4c, 0x4f, 0x47, 0x5f, 0x49, 0x4d, 0x50, 0x4f,
	0x53, 0x53, 0x49, 0x42, 0x4c, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x10, 0x02, 0x12,
	0x14, 0x0a, 0x10, 0x47, 0x52, 0x41, 0x59, 0x4c, 0x4f, 0x47, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x4d,
	0x49, 0x4e, 0x45, 0x10, 0x03, 0x42, 0x4e, 0x5a, 0x4c, 0x70, 0x6b, 0x67, 0x2e, 0x72, 0x65, 0x64,
	0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2e, 0x61, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x65, 0x64, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x3b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x41, 0x70, 0x69, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescOnce sync.Once
	file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescData = file_redcarbon_public_apis_agents_api_v1_types_proto_rawDesc
)

func file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescGZIP() []byte {
	file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescOnce.Do(func() {
		file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescData)
	})
	return file_redcarbon_public_apis_agents_api_v1_types_proto_rawDescData
}

var file_redcarbon_public_apis_agents_api_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_redcarbon_public_apis_agents_api_v1_types_proto_goTypes = []interface{}{
	(DataType)(0),                       // 0: redcarbon.public_apis.agents.api.v1.DataType
	(*AgentConfiguration)(nil),          // 1: redcarbon.public_apis.agents.api.v1.AgentConfiguration
	(*AgentConfigurationData)(nil),      // 2: redcarbon.public_apis.agents.api.v1.AgentConfigurationData
	(*SentinelOneData)(nil),             // 3: redcarbon.public_apis.agents.api.v1.SentinelOneData
	(*GrayLogImpossibleTravelData)(nil), // 4: redcarbon.public_apis.agents.api.v1.GrayLogImpossibleTravelData
	(*GrayLogDataMineData)(nil),         // 5: redcarbon.public_apis.agents.api.v1.GrayLogDataMineData
	(*GrayLogImpossibleTravelLog)(nil),  // 6: redcarbon.public_apis.agents.api.v1.GrayLogImpossibleTravelLog
	(*GrayLogDataMineResult)(nil),       // 7: redcarbon.public_apis.agents.api.v1.GrayLogDataMineResult
	(*GrayLogDataMineQuery)(nil),        // 8: redcarbon.public_apis.agents.api.v1.GrayLogDataMineQuery
	nil,                                 // 9: redcarbon.public_apis.agents.api.v1.GrayLogImpossibleTravelLog.LogsEntry
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 11: google.protobuf.Duration
}
var file_redcarbon_public_apis_agents_api_v1_types_proto_depIdxs = []int32{
	10, // 0: redcarbon.public_apis.agents.api.v1.AgentConfiguration.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: redcarbon.public_apis.agents.api.v1.AgentConfiguration.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: redcarbon.public_apis.agents.api.v1.AgentConfiguration.data:type_name -> redcarbon.public_apis.agents.api.v1.AgentConfigurationData
	3,  // 3: redcarbon.public_apis.agents.api.v1.AgentConfigurationData.sentinel_one:type_name -> redcarbon.public_apis.agents.api.v1.SentinelOneData
	4,  // 4: redcarbon.public_apis.agents.api.v1.AgentConfigurationData.graylog_impossible_travel:type_name -> redcarbon.public_apis.agents.api.v1.GrayLogImpossibleTravelData
	5,  // 5: redcarbon.public_apis.agents.api.v1.AgentConfigurationData.graylog_datamine:type_name -> redcarbon.public_apis.agents.api.v1.GrayLogDataMineData
	11, // 6: redcarbon.public_apis.agents.api.v1.GrayLogImpossibleTravelData.time_window:type_name -> google.protobuf.Duration
	9,  // 7: redcarbon.public_apis.agents.api.v1.GrayLogImpossibleTravelLog.logs:type_name -> redcarbon.public_apis.agents.api.v1.GrayLogImpossibleTravelLog.LogsEntry
	10, // 8: redcarbon.public_apis.agents.api.v1.GrayLogDataMineResult.timestamp:type_name -> google.protobuf.Timestamp
	10, // 9: redcarbon.public_apis.agents.api.v1.GrayLogDataMineQuery.search_start_time:type_name -> google.protobuf.Timestamp
	10, // 10: redcarbon.public_apis.agents.api.v1.GrayLogDataMineQuery.search_stop_time:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_redcarbon_public_apis_agents_api_v1_types_proto_init() }
func file_redcarbon_public_apis_agents_api_v1_types_proto_init() {
	if File_redcarbon_public_apis_agents_api_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentConfigurationData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SentinelOneData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrayLogImpossibleTravelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrayLogDataMineData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrayLogImpossibleTravelLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrayLogDataMineResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrayLogDataMineQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AgentConfigurationData_SentinelOne)(nil),
		(*AgentConfigurationData_GraylogImpossibleTravel)(nil),
		(*AgentConfigurationData_GraylogDatamine)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redcarbon_public_apis_agents_api_v1_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redcarbon_public_apis_agents_api_v1_types_proto_goTypes,
		DependencyIndexes: file_redcarbon_public_apis_agents_api_v1_types_proto_depIdxs,
		EnumInfos:         file_redcarbon_public_apis_agents_api_v1_types_proto_enumTypes,
		MessageInfos:      file_redcarbon_public_apis_agents_api_v1_types_proto_msgTypes,
	}.Build()
	File_redcarbon_public_apis_agents_api_v1_types_proto = out.File
	file_redcarbon_public_apis_agents_api_v1_types_proto_rawDesc = nil
	file_redcarbon_public_apis_agents_api_v1_types_proto_goTypes = nil
	file_redcarbon_public_apis_agents_api_v1_types_proto_depIdxs = nil
}
